# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Scala 3 中文站"
email: "zjx001202@gmail.com"
description: "Scala 3 中文站点"
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# logo: "/favicon.ico"
lang: zh-CN
timezone: Asia/Shanghai

# heading_anchors: true
search_enabled: false

aux_links:
  "官方网站":
    - "https://dotty.epfl.ch/"
  "改进翻译":
    - "https://github.com/Dotty-China/dotty-china.github.io"
  "捐赠支持":
    - "https://donate.glavo.site/"
  "联系维护者":
    - "https://glavo.site/about/"
  "加入 QQ 群":
    - "https://jq.qq.com/?_wv=1027&k=BCxI4ukn"

footer_content: "© 2009-2021 Aliyun.com 版权所有"

gh_edit_link: true
gh_edit_link_text: "在 GitHub 上修改此页面"
gh_edit_repository: "https://github.com/Dotty-China/dotty-china.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Build settings
remote_theme: pmarsceill/just-the-docs@v0.3.3
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - git-push.bat
  - jekyll-build.sh
  - README.md
  - docs/reference/metaprogramming/macros-spec.md
  - docs/reference/metaprogramming/reflection.md
  - docs/reference/metaprogramming/staging.md
  - docs/reference/metaprogramming/inline.md
  - docs/reference/metaprogramming/macros.md
  - docs/reference/metaprogramming/simple-smp.md
  - docs/reference/metaprogramming/tasty-inspect.md
